version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
    restart: unless-stopped

  nginx:
    image: nginx:1.17
    depends_on:
      - filerun
      - ariang
    volumes:
      - ${PWD}/conf/nginx/http.conf:/etc/nginx/nginx.conf
      - ${PWD}/ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped


  filerun:
    image: afian/filerun
    depends_on:
      - db
    links:
      - db
    volumes:
      - ${PWD}/data/filerun-userfiles:/user-files
      - ${PWD}/data/aria2-downloads:/user-files/downloads
    restart: always
 
  ariang:
    image: p3terx/ariang
    depends_on:
      aria2-pro
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

  aria2-pro:
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=<your_password> #set your RPC password
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=true
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ${PWD}/conf/aria2:/config
      - ${PWD}/data/aria2-downloads:/downloads
    # If you use 'host' network mode, then no port mapping is required.
    # This is your best choice when using IPv6.
    network_mode: host  
    #    ports:
    #      - 6800:6800
    #      - 6888:6888
    #      - 6888:6888/udp
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
